cmake_minimum_required(VERSION 4.2)
project(Lee)

set(CMAKE_CXX_STANDARD 20)

add_executable(1.Vec_Add 1.Vec_Add.cpp)
add_executable(26.RemoveSame 26.RemoveSame.cpp)
add_executable(27.RemoveElem 27.RemoveElem.cpp)
add_executable(66.Plus1 66.Plus1.cpp)
add_executable(88.Merge 88.Merge.cpp)
add_executable(118.Generate 118.Generate.cpp)
add_executable(119.GetRow 119.GetRow.cpp)
